In [1]:
import nashpy

In [36]:
import nashpy as nash

import numpy as np

# [[],[],[],[]]
A = np.array([[-1,10,10,10],[0,-1,0,10],[0,10,-1,10],[0,0,0,-1]])
B = np.array([[-1,0,0,0],[0,-1,10,0],[10,0,-1,0],[10,10,10,-1]])

rps = nash.Game(A,B)
rps

Bi matrix game with payoff matrices:

Row player:
[[-1 10 10 10]
 [ 0 -1  0 10]
 [ 0 10 -1 10]
 [ 0  0  0 -1]]

Column player:
[[-1  0  0  0]
 [ 0 -1 10  0]
 [10  0 -1  0]
 [10 10 10 -1]]

In [37]:
eqs = rps.support_enumeration()
list(eqs)

[(array([1., 0., 0., 0.]), array([0., 1., 0., 0.])),
 (array([1., 0., 0., 0.]), array([0., 0., 1., 0.])),
 (array([1., 0., 0., 0.]), array([0., 0., 0., 1.])),
 (array([0., 0., 1., 0.]), array([1., 0., 0., 0.])),
 (array([0., 0., 0., 1.]), array([1., 0., 0., 0.])),
 (array([9.01772526e-01, 8.12407681e-03, 8.93648449e-02, 7.38552437e-04]),
  array([9.09153005e-01, 7.51366120e-03, 8.26502732e-02, 6.83060109e-04]))]

In [39]:
import numpy as np

iterations = 100

np.random.seed(1)

play_counts = rps.fictitious_play(iterations=iterations)

for row_play_count, column_play_count in play_counts:

    print(row_play_count, column_play_count)

[0 0 0 0] [0 0 0 0]
[0. 1. 0. 0.] [0. 0. 0. 1.]
[1. 1. 0. 0.] [0. 0. 1. 1.]
[2. 1. 0. 0.] [0. 0. 2. 1.]
[3. 1. 0. 0.] [0. 0. 3. 1.]
[4. 1. 0. 0.] [0. 0. 4. 1.]
[5. 1. 0. 0.] [0. 0. 5. 1.]
[6. 1. 0. 0.] [0. 0. 6. 1.]
[7. 1. 0. 0.] [0. 0. 7. 1.]
[8. 1. 0. 0.] [0. 0. 8. 1.]
[9. 1. 0. 0.] [0. 0. 9. 1.]
[10.  1.  0.  0.] [ 0.  0. 10.  1.]
[11.  1.  0.  0.] [ 0.  0. 11.  1.]
[12.  1.  0.  0.] [ 0.  0. 12.  1.]
[13.  1.  0.  0.] [ 0.  0. 13.  1.]
[14.  1.  0.  0.] [ 0.  0. 14.  1.]
[15.  1.  0.  0.] [ 0.  0. 15.  1.]
[16.  1.  0.  0.] [ 0.  0. 16.  1.]
[17.  1.  0.  0.] [ 0.  0. 17.  1.]
[18.  1.  0.  0.] [ 0.  0. 18.  1.]
[19.  1.  0.  0.] [ 0.  0. 19.  1.]
[20.  1.  0.  0.] [ 0.  0. 20.  1.]
[21.  1.  0.  0.] [ 0.  0. 21.  1.]
[22.  1.  0.  0.] [ 0.  0. 22.  1.]
[23.  1.  0.  0.] [ 0.  0. 23.  1.]
[24.  1.  0.  0.] [ 0.  0. 24.  1.]
[25.  1.  0.  0.] [ 0.  0. 25.  1.]
[26.  1.  0.  0.] [ 0.  0. 26.  1.]
[27.  1.  0.  0.] [ 0.  0. 27.  1.]
[28.  1.  0.  0.] [ 0.  0. 28.  1.]
[29.  1.  0.  0.